import { Fraunces, Barlow } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import siteLogo from "@/app/assets/svg/site-logo.svg";
import Footer from "./components/Footer";

const barlow = Barlow({
  subsets: ["latin"],
  variable: "--font-barlow",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

const fraunces = Fraunces({
  subsets: ["latin"],
  variable: "--font-fraunces",
});

export const metadata = {
  title: "Coffee Roasters ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${barlow.variable} ${fraunces.variable} bg-background px-6 pt-8 pb-[4.5rem]`}
      >
        <Header siteLogo={siteLogo} />
        {children}
        <Footer siteLogo={siteLogo} />
      </body>
    </html>
  );
}
